### PR TITLE
chore(deps): remove unused dependencies and switch from Babel to SWC

### PR DESCRIPTION
**Pull request by Eldemarkki**
- Remove unused deps
- Update deps to latest versions (except `react` and `react-dom`)
- Remove `.babelrc` to use SWC

### CODE REVIEW

**Comment by Esinko** [comment]
Have you ensured this builds fine?
(ping @ahnl )

**Comment by Eldemarkki** [comment]
> Have you ensured this builds fine? (ping @ahnl )

Yes, it builds fine on my machine. It will also be checked by Vercel when the preview build is created (if/when @ahnl approves it)

**Comment by ahnl** [comment]
image

Vercel build failed.

**Comment by Eldemarkki** [comment]
Hmm, that's weird because it doesn't throw any error locally. I'll try adding that back and seeing if it fixes it.

**Pull request closed without merging**
