### PR TITLE
Various small improvements

### PR DESCRIPTION
**Pull request by Eldemarkki**
- Optimize images to make the site load faster
- Upgrade to Next.js 13 and React 18
    - This required swapping and removing some dependencies (including `@testausserveri/react-testausid`)
- Improve SEO and HTML semantics, this significantly improved Google Lighthouse scores on most pages
- Add ESLint 
- Switch from Babel to SWC, which is currently the recommended compiler by Next.js
- Removed some unused dependencies

### CODE REVIEW

**Comment by Esinko** [comment]
React-testausid should not be removed, but for now it'll have to do. Is it possible that you could do some housekeeping there too @Eldemarkki? The documentation should be easy enough to interpret. There's quite a bit of housekeeping to do there though.

**Comment by Esinko** [comment]
Also there are some conflicts in this PR atm.

**Comment by Eldemarkki** [comment]
@Esinko Fixed the conflicts. And yes I agree, `react-testausid` should not be removed, but it was slowing down development (due to not supporting React 18) and I decided it was appropriate to remove it because it wasn't even used in production. 

I've tried to fix https://github.com/Testausserveri/react-testausid/issues/2 a few times, but I've had many problems with setting up the development environment. I can try again when I have more time (likely within a 1-2 weeks).

**Comment by Esinko** [comment]
Sorry abt the close (misclick)
Anyhow, LGTM!
Merge? @ahnl

**Review by ahnl — APPROVED** [review]
Uff, hyvää duunia! Kiitos PR:ista, @Eldemarkki!

**Pull request merged**
