### PR TITLE
Migrate to typescript

### PR DESCRIPTION
**Pull request by Eldemarkki**

### CODE REVIEW

**Comment by Eldemarkki** [comment]
I didn't convert the DiscordLive component yet because #78 is still unmerged, but if/when it gets merged, I will migrate it then as well.

**Comment by Esinko** [comment]
Please continue your work on this @Eldemarkki

**Review by ahnl — APPROVED** [review]

**Comment by Eldemarkki** [comment]
Any updates @ahnl @Esinko about merging? This PR is done on my part

**Review by developerfromjokela — APPROVED** [review]

**Comment by developerfromjokela** [comment]
imo could merge right away, @Esinko not against doing that?

**Comment by developerfromjokela** [comment]
fck that, ill do it now

**Comment by ahnl** [comment]
Kiitos @Eldemarkki tästä! Näyttää hyvältä. :)

**Pull request merged**
